#!/usr/bin/env python3
"""
trace/bundle.py — fold the modular sources into the two single-file documents,
so Field Atlas 2.0 ships the same trio Field Atlas 1.x does.

    Field Atlas 2.0 (standalone-src).dc.html   canonical single file
    Field Atlas 2.0.dc.html                    the same, minus the thumbnail block
    index.html                                 the module loader — the MASTER

★ WHICH FILE IS THE MASTER IS THE OPPOSITE OF 1.x, AND DELIBERATELY SO.

In 1.x the standalone-src IS the source: you edit that file, and index.html is
generated from it. 2.0 was built the other way round — README §"Conventions" 1
and 3 make the modular ES sources the master and forbid a build step in the dev
loop — so inverting that to match 1.x would mean throwing away js/, assets/ and
the whole reason `python3 -m http.server` is all you need to work on this.

So the SHAPE matches 1.x and the direction does not:

    js/ + assets/ + data/ + index.html          <- edit these
              |
              v  python3 trace/bundle.py
    Field Atlas 2.0 (standalone-src).dc.html    <- generated, never hand-edit
    Field Atlas 2.0.dc.html                     <- generated, never hand-edit

The two .dc.html files are what you hand someone, drop on a stick, or open off
a phone with no server — one file, no network, no origin. index.html stays the
served and tested entry point. `--check` re-bundles into memory and diffs, so
CI (or a paranoid moment) can prove the three have not drifted apart.

★ HOW A SINGLE FILE STILL RUNS ES MODULES.

Inlining `import` statements does not work — a module needs a URL to resolve
relative specifiers against, and there is no URL inside a <script> tag. Fixing
that by concatenating everything and deleting the import/export lines would
work exactly until two modules declared the same local name.

Instead each module becomes its own `data:text/javascript;base64,…` URL, and
its importers get that URL substituted for the relative specifier. Modules are
encoded in dependency order, so by the time a module is encoded every specifier
inside it has already been rewritten to a data URL.

The property that makes this safe: the module map is keyed by RESOLVED URL, so
two importers that reference the same dependency produce byte-identical data
URLs, which is one URL, which is one module instance evaluated once. js/loop.js
is imported by both main.js and circuit.js and they share it, exactly as they do
over http. Base64 also cannot contain `<`, so no payload can ever close the
<script> tag it lives in.
"""
import base64, hashlib, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

STANDALONE = os.path.join(ROOT, "Field Atlas 2.0 (standalone-src).dc.html")
PLAIN      = os.path.join(ROOT, "Field Atlas 2.0.dc.html")
INDEX      = os.path.join(ROOT, "index.html")

GENERATED = (
    "<!-- GENERATED by trace/bundle.py from index.html + js/ + assets/ + data/.\n"
    "     Do not hand-edit: the next run overwrites this file. Edit the modular\n"
    "     sources and re-run `python3 trace/bundle.py`. -->\n"
)

# 1.x carries a <template id="__bundler_thumbnail"> that its plain .dc.html does
# not; that single block is the ONLY difference between its two files. 2.0 keeps
# the same relationship so the pair behaves the way Theodor already expects.
THUMBNAIL = """<template id="__bundler_thumbnail">
  <!-- The document thumbnail, carried only by the standalone-src file. This is
       the one block that distinguishes it from Field Atlas 2.0.dc.html — the
       same relationship those two files have in Field Atlas 1.x. -->
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 160" width="240" height="160">
    <rect width="240" height="160" fill="#07080a"/>
    <circle cx="176" cy="80" r="58" fill="none" stroke="#1d4359" stroke-width="1.4"/>
    <circle cx="176" cy="80" r="58" fill="#0b2130" opacity=".55"/>
    <circle cx="163" cy="58" r="2.6" fill="#c9974f"/>
    <text x="20" y="74" fill="#ece5d9" font-family="Outfit,system-ui,sans-serif"
          font-size="26" font-weight="700" letter-spacing="-.7">FIELD</text>
    <text x="20" y="102" fill="#ece5d9" font-family="Outfit,system-ui,sans-serif"
          font-size="26" font-weight="700" letter-spacing="-.7">ATLAS</text>
    <text x="20" y="126" fill="#c9974f" font-family="Outfit,system-ui,sans-serif" font-size="8"
          font-weight="600" letter-spacing="2.2">VOL. II</text>
  </svg>
</template>
"""


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return f.read()


# ------------------------------------------------------------------ modules
IMPORT_RE = re.compile(r"""(?m)^(\s*(?:import|export)\b[^'"\n]*?from\s*)(['"])([^'"]+)\2""")


def specifiers(src):
    """the relative specifiers a module imports, in source order"""
    return [m.group(3) for m in IMPORT_RE.finditer(src) if m.group(3).startswith(".")]


def resolve(base_rel, spec):
    """resolve a relative specifier against the importing module's path"""
    return os.path.normpath(os.path.join(os.path.dirname(base_rel), spec)).replace(os.sep, "/")


def data_url(rel, cache, stack=()):
    """encode `rel` and everything it imports as nested data: URLs"""
    if rel in cache:
        return cache[rel]
    if rel in stack:
        sys.exit(f"import cycle: {' -> '.join(stack + (rel,))}")

    src = read(rel)
    for spec in dict.fromkeys(specifiers(src)):
        dep = resolve(rel, spec)
        url = data_url(dep, cache, stack + (rel,))
        # replace only in the specifier position, never in prose
        src = re.sub(
            r"""(from\s*)(['"])%s\2""" % re.escape(spec),
            lambda m: m.group(1) + '"' + url + '"',
            src,
        )

    blob = base64.b64encode(src.encode("utf-8")).decode("ascii")
    cache[rel] = "data:text/javascript;base64," + blob
    return cache[rel]


# -------------------------------------------------------------------- build
def build(with_thumbnail):
    html = read("index.html")
    cache = {}

    # `?v=<hash>` is index.html's cache-busting (see stamp_index) and is not part
    # of any path on disk — strip it before opening anything
    bare = lambda href: href.split("?")[0]

    # <link rel="stylesheet" href="assets/*.css">  ->  inline <style>
    def inline_css(m):
        href = bare(m.group(1))
        if href.startswith("http"):
            return m.group(0)                     # Google Fonts stays a link
        return "<style>\n/* %s */\n%s</style>" % (href, read(href))

    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_css, html)

    # <script type="module" src="js/main.js">  ->  inline module importing it
    def inline_js(m):
        entry = bare(m.group(1))
        return ('<script type="module">\n/* %s and every module it imports, each '
                'inlined as its own\n   data: URL — see trace/bundle.py */\n'
                'import "%s";\n</script>' % (entry, data_url(entry, cache)))

    html = re.sub(r'<script type="module" src="([^"]+)"></script>', inline_js, html)

    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + GENERATED, 1)
    if with_thumbnail:
        html = html.replace("</body>", THUMBNAIL + "</body>", 1)
    return html, cache


def stamp_index():
    """Put a content hash on index.html's own asset URLs.

    ★ The .dc.html files inline everything, so they can never be served half
    stale. index.html can, and once was: Theodor got a page whose JS had
    reloaded and whose assets/app.css had not, so the panel opened, locked the
    scroll, and rendered nothing — "everything just froze". `http.server` sends
    no Cache-Control, and a response with no stated freshness is one the browser
    may age by its own heuristic.

    trace/serve.py answers that locally with `no-store`. This answers it for
    anywhere index.html is actually hosted: `?v=<hash of the file>` changes the
    URL whenever the bytes change, so a cached copy can only ever be served for
    bytes that are still current. Nothing to remember to bump.
    """
    html = read("index.html")
    def restamp(m):
        attr, href = m.group(1), m.group(2).split("?")[0]
        if href.startswith("http") or not os.path.exists(os.path.join(ROOT, href)):
            return m.group(0)
        h = hashlib.sha1(read(href).encode("utf-8")).hexdigest()[:8]
        return '%s="%s?v=%s"' % (attr, href, h)
    out = re.sub(r'(href|src)="([^"]+\.(?:css|js))(?:\?[^"]*)?"', restamp, html)
    if out != html:
        with open(INDEX, "w", encoding="utf-8") as f:
            f.write(out)
    return out != html


def main():
    check = "--check" in sys.argv
    if not check and stamp_index():
        print("  stamped index.html asset URLs with content hashes")
    standalone, cache = build(True)
    plain, _ = build(False)

    if check:
        bad = 0
        for path, want in ((STANDALONE, standalone), (PLAIN, plain)):
            name = os.path.basename(path)
            if not os.path.exists(path):
                print(f"  MISSING  {name}"); bad += 1
            elif open(path, encoding="utf-8").read() != want:
                print(f"  STALE    {name} — re-run `python3 trace/bundle.py`"); bad += 1
            else:
                print(f"  ok       {name}")
        # the one invariant the pair has to keep, same as 1.x
        if os.path.exists(STANDALONE) and os.path.exists(PLAIN):
            a = open(STANDALONE, encoding="utf-8").read()
            b = open(PLAIN, encoding="utf-8").read()
            if a.replace(THUMBNAIL, "", 1) == b:
                print("  ok       standalone-src == plain + the thumbnail block, exactly")
            else:
                print("  BROKEN   the two .dc.html files differ by more than the thumbnail"); bad += 1
        sys.exit(1 if bad else 0)

    for path, text in ((STANDALONE, standalone), (PLAIN, plain)):
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"  wrote  {os.path.basename(path):44} {len(text) / 1024:8.1f} KB")
    print(f"\n  {len(cache)} modules inlined: " + ", ".join(sorted(cache)))


if __name__ == "__main__":
    main()
