/* ===========================================================================
 * trace/fonts.mjs — GENERATOR for assets/fonts.css
 *
 *     node trace/fonts.mjs            # regenerate from the woff2 in fonts/
 *     node trace/fonts.mjs --fetch    # re-download from Google first
 *
 * Outfit, variable, weights 100–900, subsets latin + latin-ext. `fonts/` holds
 * the woff2 as committed source; this writes them into `assets/fonts.css` as
 * base64 `data:` URIs.
 *
 * ★ THE data: URIs ARE NOT AN OPTIMISATION — they are the only encoding that is
 * correct in both places the stylesheet ends up.
 *
 *   - Served, the sheet is `assets/tokens.css`'s neighbour, so a relative
 *     `url()` would resolve against `assets/`.
 *   - Inlined, trace/bundle.mjs folds every stylesheet into a `<style>` in
 *     index.html, where the SAME relative `url()` resolves against the repo
 *     root instead — a different file, or more likely none.
 *   - And the two .dc.html files are opened off file:// as a single document
 *     with no origin and no sibling `fonts/` directory at all.
 *
 * A `data:` URI has no base to be relative to, so it is right in all three. It
 * is also why this is a separate sheet rather than a block at the top of
 * tokens.css: 61 KB of base64 would bury the one file in the repo whose whole
 * job is to be read.
 *
 * The subsetting is Google's own. latin already covers å ä ö — Örnsköldsvik
 * renders off the first file — and latin-ext is carried for the rest of the
 * range rather than dropped, because it is 15 KB and the alternative is
 * discovering a missing glyph in a venue name later.
 * ======================================================================== */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT  = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONTS = join(ROOT, 'fonts');
const OUT   = join(ROOT, 'assets', 'fonts.css');

/* Pinned to the exact files behind the css2 request the page used to make:
   https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap
   Google returns the same full-axis file for any wght range, so 100..900 costs
   nothing over the 300..800 the page actually uses. */
const FACES = [
  {
    subset: 'latin-ext',
    file: 'outfit-latin-ext.woff2',
    url: 'https://fonts.gstatic.com/s/outfit/v15/QGYvz_MVcBeNP4NJuktqQ4E.woff2',
    range: 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF',
  },
  {
    subset: 'latin',
    file: 'outfit-latin.woff2',
    url: 'https://fonts.gstatic.com/s/outfit/v15/QGYvz_MVcBeNP4NJtEtq.woff2',
    range: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
  },
];

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

mkdirSync(FONTS, { recursive: true });

if (process.argv.includes('--fetch')) {
  for (const f of FACES) {
    const res = await fetch(f.url, { headers: { 'User-Agent': UA } });
    if (!res.ok) { console.error(`  ${f.file}: HTTP ${res.status}`); process.exit(1); }
    writeFileSync(join(FONTS, f.file), Buffer.from(await res.arrayBuffer()));
    console.log(`  fetched fonts/${f.file}`);
  }
}

const blocks = [];
let total = 0;

for (const f of FACES) {
  const path = join(FONTS, f.file);
  if (!existsSync(path)) {
    console.error(`missing fonts/${f.file} — run: node trace/fonts.mjs --fetch`);
    process.exit(1);
  }
  const buf = readFileSync(path);
  // wOF2 or it is not what we think it is — a Google error page would otherwise
  // be base64'd straight into the stylesheet and fail silently as a bad font.
  if (buf.slice(0, 4).toString('ascii') !== 'wOF2') {
    console.error(`fonts/${f.file} is not a woff2 file`);
    process.exit(1);
  }
  total += buf.length;
  blocks.push(
`/* ${f.subset} — fonts/${f.file}, ${buf.length} bytes */
@font-face {
  font-family: 'Outfit';
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2');
  unicode-range: ${f.range};
}`);
}

const css = `/* GENERATED by trace/fonts.mjs — do not hand-edit. Source: fonts/*.woff2.
 *
 * Outfit, variable, 100–900. Self-hosted, and inlined as data: URIs so the one
 * stylesheet is correct served, inlined into index.html by trace/bundle.mjs, and
 * opened off file:// inside the .dc.html pair. See the header of trace/fonts.mjs.
 *
 * This file is the reason the page makes ZERO cross-origin requests. Nothing here
 * may grow a url() that points anywhere but at itself.
 */

${blocks.join('\n\n')}
`;

writeFileSync(OUT, css, 'utf8');
console.log(`  wrote assets/fonts.css  ${(css.length / 1024).toFixed(1)} KB` +
            `  (from ${(total / 1024).toFixed(1)} KB of woff2)`);
